name: Update News Feed
on:
  schedule:
    - cron: '0 * * * *' # Her saat başı çalışır
  workflow_dispatch: # Manuel tetikleme
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.7' # Senin Python sürümün
      - name: Install dependencies
        run: pip install feedparser beautifulsoup4 requests lxml os json
      - name: Run aa_news
        run: python aa_news.py 
      - name: Run science
        run: python science.py 
      - name: Run ensonhaber
        run: python ensonhaber.py 
      - name: Run news      
        run: python news.py
      
      - name: Deploy to Netlify
        run: npm install -g netlify-cli && netlify deploy --prod --dir dist
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}