name: Update News Feed
on:
  schedule:
    - cron: '*/5 * * * *' # Her saat başı çalışır
  workflow_dispatch: # Manuel tetikleme
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.7' # Senin Python sürümün
      - name: Install Python dependencies
        run: pip install feedparser beautifulsoup4 requests lxml
      - name: Run aa_news
        run: python aa_news.py 
      - name: Run science
        run: python science.py 
      - name: Run ensonhaber
        run: python ensonhaber.py 
      - name: Run news      
        run: python news.py
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Netlify ile uyumlu
      - name: Install Node.js dependencies
        run: npm install
      - name: Verify vite installation
        run: npx vite --version # vite'in yüklendiğini kontrol et
      - name: Build
        run: npm run build
      - name: Install Netlify CLI
        run: npm install -g netlify-cli@latest # En son sürümü yükle
      - name: Deploy to Netlify
        run: netlify deploy --prod --dir dist  # Tekrar dene
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}